# Generated by Django 3.1.7 on 2021-03-14 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_status_salvage', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=1900)),
                ('color', models.CharField(max_length=200)),
                ('vin', models.CharField(max_length=200)),
                ('VehModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarData.vehmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(default=0)),
                ('lot', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarData.vehicle')),
            ],
        ),
    ]
